package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"mime"
	"os"
	"path/filepath"
	"strings"
	"time"

	"google.golang.org/genai"
)

var model = flag.String("model", "gemma-4-31b-it", "the model name, e.g. gemma-4-31b-it")

func processImage(imgID int64, colID string) {
	fmt.Println("starting processing")
	//get image data from db
	var img Image
	var col Collection
	dbMutex.RLock()
	err := db.QueryRow(
		"SELECT name, type, alcohol_content, net_content, origin, filename FROM images WHERE id = ?",
		imgID,
	).Scan(&img.Name, &img.Type, &img.Alcohol_content, &img.Net_content, &img.Origin, &img.Filename)
	if err != nil {
		log.Fatal(err)
	}
	err = db.QueryRow(
		"SELECT name, address FROM collections WHERE id = ?",
		colID,
	).Scan(&col.Name, &col.Address)
	if err != nil {
		log.Fatal(err)
	}
	dbMutex.RUnlock()

	fmt.Println("processing uploads/", img.Filename)

	//create gemini API call
	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	//response schema
	var responseSchema genai.Schema
	err = json.Unmarshal([]byte(`{
		"type": "object",
		"properties": {
			"unfiltered_text": {
			"type": "string"
			},
			"issues": {
			"type": "array",
			"items": {
				"type": "string"
			}
			},
			"potential_issues": {
			"type": "array",
			"items": {
				"type": "string"
			}
			},
			"legal": {
			"type": "boolean"
			},
			"unsure": {
			"type": "boolean"
			}
		},
		"required": [
			"unfiltered_text",
			"legal",
			"unsure"
		],
		"propertyOrdering": [
			"unfiltered_text",
			"issues",
			"potential_issues",
			"legal",
			"unsure"
		]
	}`), &responseSchema)
	if err != nil {
		log.Fatal(err)
	}

	systemPrompt, err := os.ReadFile("prompt.txt")
	if err != nil {
		log.Fatal("Failed to read system prompt:", err)
	}

	//autogenerated gemini config
	var config *genai.GenerateContentConfig = &genai.GenerateContentConfig{
		MediaResolution: "MEDIA_RESOLUTION_HIGH",
		SystemInstruction: &genai.Content{
			Parts: []*genai.Part{
				{Text: string(systemPrompt)},
			},
		},
		ThinkingConfig: &genai.ThinkingConfig{
			ThinkingLevel: "HIGH",
		},
		ResponseMIMEType: "application/json",
		ResponseSchema:   &responseSchema,
	}

	//load image
	data, err := os.ReadFile("uploads/" + img.Filename)
	if err != nil {
		log.Fatal(err)
	}

	//setup prompt
	var contents = []*genai.Content{
		{
			Role: "user",
			Parts: []*genai.Part{
				{

					Text: fmt.Sprintf(`Name: %s
Type: %s
Alcohol content: %s
Net content: %s
National origin: %s
Company name: %s
Company address: %s`, img.Name, img.Type, img.Alcohol_content, img.Net_content, img.Origin, col.Name, col.Address),
				},
				{
					InlineData: &genai.Blob{
						Data:     data,
						MIMEType: mime.TypeByExtension(filepath.Ext(img.Filename)),
					},
				},
			},
		},
	}

	// Call the GenerateContent method.
	result, err := aiClient.Models.GenerateContent(ctx, *model, contents, config)
	var text string
	if err == nil {
		text = result.Text()
		text = strings.ReplaceAll(text, "`", "") //remove outer markdown formatting
	} else {
		fmt.Println("AI error:", err)
		text = `{
  "unfiltered_text": "Image processing failed, manual review required",
  "issues": [],
  "potential_issues": ["Image processing failed, manual review required"],
  "legal": false,
  "unsure": true
}`
	}

	fmt.Println(text)

	//update db
	dbMutex.Lock()
	_, err = db.Exec("UPDATE images SET processed = 1 WHERE id = ?", imgID)
	if err != nil {
		fmt.Println("Processing Error 1", err)
	}
	_, err = db.Exec("UPDATE images SET processing_data = ? WHERE id = ?", text, imgID)
	if err != nil {
		fmt.Println("Processing Error 2", err)
	}
	_, err = db.Exec("UPDATE collections SET processed = processed + 1 WHERE id = ?", colID)
	if err != nil {
		fmt.Println("Processing Error 3", err)
	}
	dbMutex.Unlock()
}
